// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv9gLLrD2D83tJiN_WY4VQh7vYQVJ_EbM',
    appId: '1:938009266159:web:a1c4c0b72ee3958cd9981a',
    messagingSenderId: '938009266159',
    projectId: 'switchskills-1c163',
    authDomain: 'switchskills-1c163.firebaseapp.com',
    storageBucket: 'switchskills-1c163.appspot.com',
    measurementId: 'G-DLF63H3NRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf5jZsmbZWAq5sfGkrb3iOgxC6Sdm6ZHk',
    appId: '1:938009266159:android:e11e7a21f5c2bd99d9981a',
    messagingSenderId: '938009266159',
    projectId: 'switchskills-1c163',
    storageBucket: 'switchskills-1c163.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCigvqkrxgmssMofQ90o6HT8J8miin1_H0',
    appId: '1:938009266159:ios:c46330605d33f442d9981a',
    messagingSenderId: '938009266159',
    projectId: 'switchskills-1c163',
    storageBucket: 'switchskills-1c163.appspot.com',
    iosClientId: '938009266159-it34u93g7mpun22qrskmf8v8ngvrrunj.apps.googleusercontent.com',
    iosBundleId: 'com.example.switchskilss',
  );
}
